name: Run Snyk Test
on:
  push:
    branches:
      - develop

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

      - name: Snyk install
              uses: snyk/actions/setup@master
            
            - name: Snyk test
              run: snyk test
              env: 
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}